Remove -fourdigits from version name as it gives version conflicts in buildout.
It seems buildout can't check this type of version name, we got:
Error: The requirement (‘dm.zope.saml2>2.0b7’) is not allowed by your [versions] constraint (3.1b3-fourdigits)